---
- name: config | Ensuring All Paths Exist
  file:
    dest: "{{ item['path'] }}"
    owner: "{{ _nfs_server_owner }}"
    group: "{{ _nfs_server_group }}"
    mode: "{{ item['mode']|default(omit) }}"
    state: "directory"
  become: true
  with_items: '{{ nfs_server_exports }}'
  when: nfs_server_exports is defined

- name: config | Configuring /etc/exports
  template:
    src: "etc/exports.j2"
    dest: "/etc/exports"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
  become: true
  notify: "restart {{ _nfs_server_service }}"
